apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: much-to-do-ns
type: Opaque
data:
  # Base64 encoded 'admin' and 'password'
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQ=
