apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: much-to-do-ns
type: Opaque
data:
  # The combined string from your terminal output
  mongo-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy9tdWNodG9kbz9hdXRoU291cmNlPWFkbWlu
